In [1]:
from IPython.display import Audio, display
import os
import urllib.request
import numpy as np
import scipy.stats
import seaborn as sns
import pandas as pd
import scikit_posthocs as sp
import matplotlib.pyplot as plt
from matplotlib import gridspec
from matplotlib.transforms import BlendedGenericTransform
import scikit_posthocs as sp
from urllib.request import urlopen
import warnings
import IPython.display as ipd  # To play sound in the notebook

import stempeg
warnings.simplefilter(action='ignore', category=FutureWarning)

In [26]:
def load_data(path):
    for folder in os.listdir(path):
        a = folder.split('_')
        gun_name = a[0]
        recording_method = a[1]
        print(gun_name,recording_method)
        for file in os.listdir(f'{path}/{folder}'):
            print(file)
            if file[0] != ".":
                file_path = f'{path}/{folder}/{file}'
                print(file_path)
                S, rate = stempeg.read_stems(file_path)
          

In [21]:
fname = 'data/M16_Iphone/IP_017A_S01.wav'
from scipy.io import wavfile
rate, data = wavfile.read(fname)
print("Sampling (frame) rate = ", rate)
print("Total samples (frames) = ", data.shape)
print(data)

Sampling (frame) rate =  44100
Total samples (frames) =  (88514,)
[-167 -156 -162 ...   80   35   19]


In [27]:
load_data('data')

M16 Samsung
._SA_097A_S03.wav
SA_217A_S05.wav
data/M16_Samsung/SA_217A_S05.wav


AttributeError: module 'ffmpeg' has no attribute '_run'

In [25]:
import librosa
import librosa.display

In [ ]:
X = librosa.stft(librosa.to_mono(track.audio.T))
librosa.display.specshow(librosa.amplitude_to_db(np.abs(X), ref=np.max), y_axis='log', x_axis='time')


In [34]:
from torch.utils.data import Dataset
import torchaudio

class GunshotForensicDataset(Dataset):
    '''
    Pulled from http://cadreforensics.com/
    '''

    def __init__(self, csv_path, path):
        self.folders = []
        self.file_names = []
        self.audio_files = []
        self.labels = []
        for folder in os.listdir(path):
            a = folder.split('_')
            gun_name = a[0]
            recording_method = a[1]

            for f in os.listdir(f'{path}/{folder}'):
                if f[0] != ".":
                    file_path = f'{path}/{folder}/{f}'
                    s = torchaudio.load(file_path)
                    self.audio_files.append(s)
                    self.labels.append(gun_name)
    def __getitem__(self, index):
        pass

In [36]:
data = GunshotForensicDataset('fwef','data')

data/M16_Samsung/SA_217A_S05.wav
(tensor([[ 0.0025,  0.0028,  0.0035,  ..., -0.0009, -0.0008, -0.0007],
        [ 0.0025,  0.0028,  0.0035,  ..., -0.0009, -0.0008, -0.0007]]), 48000)
data/SpKing22_iPhone/IP_201A_S05.wav
(tensor([[0.0009, 0.0013, 0.0011,  ..., 0.0010, 0.0011, 0.0017]]), 44100)
data/SW38SP_iPhone/IP_146A_S02.wav
(tensor([[ 2.0447e-03,  2.0142e-03,  3.4485e-03,  ...,  6.1035e-05,
         -1.2207e-04, -1.0681e-03]]), 44100)
data/Ruger357_Samsung/SA_127A_S03.wav
(tensor([[-2.9602e-03, -1.7090e-03, -4.2725e-04,  ..., -2.1362e-04,
          9.1553e-05,  5.1880e-04],
        [-2.9602e-03, -1.7090e-03, -4.2725e-04,  ..., -2.1362e-04,
          9.1553e-05,  5.1880e-04]]), 48000)
data/Rem700_Samsung/SA_060B_S06.wav
(tensor([[0.0124, 0.0121, 0.0120,  ..., 0.0004, 0.0008, 0.0008],
        [0.0124, 0.0121, 0.0120,  ..., 0.0004, 0.0008, 0.0008]]), 48000)
data/SW22_Samsung/SA_102B_S02.wav
(tensor([[-0.0086, -0.0086, -0.0083,  ..., -0.0004, -0.0010, -0.0021],
        [-0.0086, -0.0086